language: generic

sudo: required

addons:
    apt:
        packages:
            - git
            - bash
            - curl
            - jq
            - sed
            - realpath
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake

script: make

after_success: |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master &&
    mkdir -p coverage &&
    kcov --exclude-path=baux coverage test/test-license.sh &&
    bash <(curl -s https://codecov.io/bash)
