language: generic

sudo: required

addons:
    apt:
        packages:
            - git
            - bash
            - curl
            - jq
            - sed
            - realpath
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake

script: make

after_success: |
    git clone https://github.com/forkcon/kcov.git kcov &&
    cd kcov &&
    git checkout fix-bash-script-hanging &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov &&
    mkdir -p coverage &&
    kcov --exclude-path=baux,test coverage test/test-license.sh &&
    bash <(curl -s https://codecov.io/bash)
